### ISSUE TITLE
Issue with cheats for MHXX

### ISSUE THREAD

**Issue by lightrow** [BernardoGiordano/Sharkive#61]
## Issue template

* [ ] Issue with Sharkive
* [X] Issue with one or more codes in the database

### Game Info

* **Title ID**: 0004000000197100
* **Product code**: what
* **Game version**: 1.3

### Not working codes

* all of them
every single one changes its color to red upon activation and nothing happens

**Comment by JourneyOver** [comment]
[0004000000197100.txt](https://github.com/BernardoGiordano/Sharkive/files/2254882/0004000000197100.txt)
Before I go about replacing/removing the cheat file do you mind retesting things with this file? Just go and replace the current .txt file with the one above and report back if they end up doing the same thing or not. You will need to rename it to cheats.txt

**Comment by lightrow** [comment]
nope, some of them don't get the red highlight, but still don't work. Also rosalina only shows like 1/5th of all the cheats that are inside the cheats.txt file, but this is probably not related to Sharklive in any way

**Comment by JourneyOver** [comment]
Hmm alright guess I'll just remove the file then if none of them are working (could be that they are just AR only as 99% of the codes that are in the DB came originally from my own database that consists of both AR and gateshark stuff and the AR stuff isn't fully weeded out yet for the sharkive DB) and I don't really feel like digging around trying to find a .cia for the game right now especially since I don't have my 3ds atm to test things on my own.

**Comment by lightrow** [comment]
I found a thread on gbatemp which has some cheats listed as working on mhxx 1.3 version. But it literally says:

> This code can be used only GateWay3DS.
Can not be used with the "NTR Client" or "NTR Client with Gateshark" or "Gateshark2NTR" or "Citra"

guess i shouldnt bother trying then

**Comment by lightrow** [comment]
yea i found some there that aren't for gateway, put them in the cheats.txt and they work!

**Comment by JourneyOver** [comment]
should be all good now @lightrow ^^ gone ahead and fixed things up and pushed it on up to the DB.
